[package]
description = "Service mesh for network infrastructure and robotics"
edition = "2024"
license = "MIT OR Apache-2.0"
name = "flor"
repository = "https://github.com/rete-labs/flor"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
error-stack = "0.7"
fast-socks5 = "1.0"
fundle = "0.3"
glob = "0.3"
husky-rs = "0.3"
log = { version = "0.4", features = ["std"] }
mockall_double = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }

# Using "ring" backend across all crypto libs, as quinn uses it by default
anstyle = "1.0"
pem = "3"
quinn = { version = "0.11" }
rcgen = { version = "0.14", default-features = false, features = ["pem", "ring", "x509-parser"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
spiffe = { version = "0.15", default-features = false, features = ["x509"] }
time = { version = "0.3", default-features = false, features = ["std"] }
tracing = "0.1"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
x509-parser = { version = "0.18", features = ["verify"] }

[dev-dependencies]
assert_cmd = "2"
ctor = "0.8"
mockall = "0.14"
serial_test = "3.4"
tempfile = "3"
